### ISSUE TITLE
.NET Standard based version

### ISSUE THREAD

**Issue by mikanyg** [BredStik/HangFire.Windsor#10]
Any plans to migrate to .NET Standard. Just added the package to a .NET Standard 2.0 package we have, and VS complained that HangFire.Windsor is not .NET Standard and was restored using .NET Framework 4.6.2 instead. As we need to use our packages in .NET Core, I had to find alternatives to using the package.

**Comment by BredStik** [comment]
Good point.  According to the .NET portability analyzer, it should be pretty straightforward.   I'll try to do it soon.

**Comment by BredStik** [comment]
@mikanyg 

Targeting NetStandard 2.0 would require to upgrade the dependency to Castle from 3.3 to at least 4.0.  Is that an issue?  Do people still use 3.3?

**Comment by mikanyg** [comment]
We have long ago upgraded to v4 and are now going to v5. You could simply bump the major version to indicate the potential breaking change.

**Comment by BredStik** [comment]
@mikanyg 

This matches the release of the 2.0.1 version of the Nuget package found here:

https://www.nuget.org/packages/HangFire.Windsor/2.0.1

Enjoy!
