### ISSUE TITLE
What about releasing resolved jobs?

### ISSUE THREAD

**Issue by hikalkan** [BredStik/HangFire.Windsor#3]
In Windsor, we should release an object we resolved. So, how it will be released?

**Comment by IanYates** [comment]
I ended up rewriting this in my own codebase where I have a Windsor Job Activator that works in tandem with a globally installed job filter.
The job filter sees the start of a job, which happens on a specific thread.  It tells the job activator of this, which sets up a child Windsor container in a thread local.  On the same thread, Hangfire then executes the job and asks the Windsor Job Activator to create its types.  The job activator gets the child container from the thread local and does its thing.

When the job is finished, the job filter tells the job activator to dispose of the child container created specifically for the thread.

I got the idea from reading a few different approaches people had taken with other IOC containers and Hangfire.  Note that I think Hangfire 1.5+ has some additional IOC hooks which may make some of this no longer required.

I put an extract of my code in a gist
https://gist.github.com/IanYates/29180ce09c41e42b9a7e

Hope it's of some help.

**Comment by IanYates** [comment]
@BredStik - could I perhaps create a PR against this repo and, if so, could you then update NuGet?

**Comment by hikalkan** [comment]
I implemented in other way. Can you check it: https://gist.github.com/IanYates/29180ce09c41e42b9a7e#gistcomment-1677285
Thanks a lot.

**Comment by IanYates** [comment]
Hi @hikalkan - I replied on the Gist

**Comment by IanYates** [comment]
(referring to your comment on the Gist)
The job activator scope is the new thing introduced in Hangfire 1.5. The old approach still works but the newer approach is probably better. I haven't updated to 1.5 since I didn't want to reverify the correct Windsor behaviour again.

In the code you've posted I don't see any Windsor usage - is it hidden behind the IIocResolver?

The approach seems pretty sound though. Certainly it's less hacky :)

Thanks!

**Comment by hikalkan** [comment]
IIocResolver is ASP.NET Boilerplate's IOC abstraction. You can use same by sending Windsor Container directly. As I test, it's properly working.

**Comment by BredStik** [comment]
I created a new branch specifically to support 1.5 + version of Hangfire.  Please feel free to submit a pull request that would use the job activator scope.

**Comment by BredStik** [comment]
Thanks to @jeroenvervaeke , this issue is closed!  Will update the nuget package soon.

**Comment by BredStik** [comment]
Nuget version 1.1.0 released with the new changes!
