### ISSUE TITLE
Hangfire Windsor doesn't work with Hangfire 1.5.3

### ISSUE THREAD

**Issue by ArneKlein** [BredStik/HangFire.Windsor#4]
The current nuget package allows to update Hangfire to 1.5.6 however it breaks afterwards.

Maybe I'm doing something wrong, however I always get the message that it depends on Hangfire 1.5.3

Any help would be appreciated :)

**Comment by BredStik** [comment]
I will take a look when I have a few minutes.  There shouldn't be any breaking changes from 1.5.3 to 1.5.6 so I will try not to depend on a specific implementation.  In the meantime, you can try redirecting assembly versions allowing 1.5.6 to be used whenever 1.5.3 is requested like shown here [https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx](url)

**Comment by BredStik** [comment]
I created a new version to support 1.5.6.  Please see if it fixes your issue by installing it with this command (it is not listed yet):
Install-Package HangFire.Windsor -Version 1.0.5981.19913

**Comment by ArneKlein** [comment]
Thank you very much for the fix :) It is working now
