### ISSUE TITLE
Wrong Castle.Windsor reference in v1.1.0

### ISSUE THREAD

**Issue by teedj** [BredStik/HangFire.Windsor#8]
Hi,
I tried to update the Hangfire.Windsor package to v1.1.0 that requires at least Castle.Windsor 3.3.0 but
after the update my project does not compiles because the Hangfire.Windsor assembly requires a reference to Castle.Windsor 3.4.0.

![image](https://user-images.githubusercontent.com/9964553/31077484-fd8d801c-a77e-11e7-8ad7-a3d4723deaa2.png)

I noticed a mismatch between the package.config file and the nuspec in the source repo but I don't know what's the correct version of castle to use.
Unfortunatly I cannot update Castle to v3.4.0 and so I cannot update Hangfire.Windsor. Can you solve this issue?

**Comment by BredStik** [comment]
I'm pretty sure it would work fine with 3.3.0.  I can update my project to use 3.3.0, but in the meantime, you could use the bindingRedirect feature of .net to use assembly version 3.3.0 whenever 3.4.0 is requested.  See how [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions).

**Comment by BredStik** [comment]
Just released nuget package 1.1.1 that fixes this issue.
